import { NextResponse } from "next/server";
import jsPDF from "jspdf";

export async function POST(request: Request) {
  try {
    const data = await request.json();
    const { roleName, projectName, brand, location, productionDates, videos, photos, filmingNotes } = data;

    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const w = doc.internal.pageSize.getWidth();
    const m = 15;
    let y = 0;

    // Header bar
    doc.setFillColor(0, 0, 0);
    doc.rect(0, 0, w, 20, "F");
    doc.setTextColor(201, 168, 76);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Script To Cast", m, 13);

    // Job info table
    y = 28;
    doc.setFillColor(240, 240, 240);
    doc.rect(m, y, w - m * 2, 6, "F");
    doc.setTextColor(0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("JOB INFORMATION", m + 2, y + 4.5);
    y += 8;

    const info = [
      ["Project:", projectName],
      ["Brand:", brand],
      ["Location:", location],
      ["Production Dates:", productionDates],
      ["Role Name:", roleName],
    ].filter(([, v]) => v);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    for (const [label, value] of info) {
      doc.setFont("helvetica", "bold");
      doc.text(label, m + 2, y + 3.5);
      doc.setFont("helvetica", "normal");
      doc.text(value, m + 40, y + 3.5);
      y += 5;
    }
    y += 5;

    // Step 1: Online Talent Form
    doc.setFillColor(0, 0, 0);
    doc.rect(m, y, w - m * 2, 6, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("Step 1: Online Talent Form", m + 2, y + 4.5);
    y += 10;
    doc.setTextColor(0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("Please complete the Online Talent Form. Submissions cannot be accepted without a completed form.", m, y);
    y += 8;

    // Step 2: Record Audition Videos
    doc.setFillColor(0, 0, 0);
    doc.rect(m, y, w - m * 2, 6, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("Step 2: Record Audition Videos", m + 2, y + 4.5);
    y += 10;
    doc.setTextColor(0);

    for (let i = 0; i < (videos || []).length; i++) {
      const v = videos[i];
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.text(`VIDEO ${i + 1} (LABEL IT '${v.label}')`, m, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(v.description, w - m * 2);
      doc.text(lines, m, y);
      y += lines.length * 4 + 4;
      if (y > 270) { doc.addPage(); y = 15; }
    }

    // Step 3: Photos
    if (photos?.length) {
      doc.setFillColor(0, 0, 0);
      doc.rect(m, y, w - m * 2, 6, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.text("Step 3: Photos", m + 2, y + 4.5);
      y += 10;
      doc.setTextColor(0);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      photos.forEach((p: string, i: number) => {
        doc.text(`${i + 1}. ${p}`, m + 2, y);
        y += 5;
      });
      y += 3;
    }

    // Filming Notes
    if (filmingNotes?.length) {
      if (y > 240) { doc.addPage(); y = 15; }
      doc.setFillColor(0, 0, 0);
      doc.rect(m, y, w - m * 2, 6, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.text("Filming Notes", m + 2, y + 4.5);
      y += 10;
      doc.setTextColor(0);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      filmingNotes.forEach((n: string, i: number) => {
        const lines = doc.splitTextToSize(`${i + 1}. ${n}`, w - m * 2 - 4);
        doc.text(lines, m + 2, y);
        y += lines.length * 4 + 2;
      });
    }

    // Footer
    doc.setTextColor(150);
    doc.setFontSize(7);
    doc.text("Generated by Script To Cast — scripttocast.com", m, 290);

    const buffer = new Uint8Array(doc.output("arraybuffer"));
    return new NextResponse(buffer as any, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="Self-Tape_${roleName.replace(/\s+/g, "_")}.pdf"`,
      },
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
